url: https://charlieallen.github.io/
baseurl: 

# Site settings
title: Charlie Allen
email: charlieallen81@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spangle_cat
  - title: github
    url: http://github.com/CharlieAllen

# Postal address (add as many lines as necessary)
address:
  - line: London UK

# Build settings
markdown: kramdown
permalink: pretty